spring.application.name=TriDuc_Clinic

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/pk_triduc
spring.datasource.username=postgres
spring.datasource.password=Hung0968@
spring.jpa.hibernate.ddl-auto=update
#Turn off spring boot banner
spring.main.banner-mode=off

#Reduce logging level. Set logging level to warn
#logging.level.root=warn

spring.security.user.name = hungvit
spring.security.user.password = Hung2002@

TWILIO.ACCOUNT_SID=ACd3b7669a557180e82b825576fc7cedc1
TWILIO.AUTH_TOKEN=fd3a011bf6208cd2a7649628fd647b08
TWILIO.PHONE_NUMBER=+18883755830